# Generated by Django 5.2.2 on 2025-09-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=20)),
                ("release_date", models.CharField(max_length=20)),
                ("imdb_rating", models.CharField(max_length=20)),
                ("rottentomatoes_rating", models.CharField(max_length=20)),
                ("language", models.CharField(max_length=20)),
                ("poster", models.ImageField(upload_to="posters/")),
                ("trailer_link", models.URLField(max_length=500)),
                ("actors", models.ManyToManyField(to="main.actor")),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.director",
                    ),
                ),
            ],
        ),
    ]
