# Generated by Django 5.0.2 on 2024-04-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moviename_info_crew_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor1', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Actor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor2', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMDB', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releasedate', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='RottenTomatoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rottentomatoes', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
    ]
