# Generated by Django 5.0.2 on 2024-04-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actor1_actor2_desc_director_duration_genre_imdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
    ]
