# Generated by Django 5.0.2 on 2024-04-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='moviename',
        ),
        migrations.RemoveField(
            model_name='info',
            name='moviename',
        ),
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
