# Generated by Django 5.0.2 on 2024-04-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('releasedate', models.CharField(max_length=20)),
                ('IMDB', models.CharField(max_length=20)),
                ('rottentomatos', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=20)),
                ('script', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor1', models.CharField(max_length=20)),
                ('Actor2', models.CharField(max_length=20)),
                ('Actor3', models.CharField(max_length=20)),
                ('Actress1', models.CharField(max_length=20)),
                ('Actress2', models.CharField(max_length=20)),
                ('moviename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moviename')),
            ],
        ),
    ]
